/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	G:/Compete/Advanced_OK/rgmii_ethernet/al_ip/BUFG1.v
 ** Date	:	2022 07 02
 ** TD version	:	5.0.30786
\************************************************************/

`timescale 1ns / 1ps

module BUFG1 ( i, o );
		output 		o;
		input  		i;

		EG_LOGIC_BUFG bufg(
		.i(i),
		.o(o));

endmodule