/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	D:/EG4S20/EG4S20/Codes/rgmii_ethernet/al_ip/FIFO.v
 ** Date	:	2021 08 05
 ** TD version	:	5.0.30786
\************************************************************/

`timescale 1ns / 1ps

module FIFO (
	rst,
	di, clk, we,
	do, re,
	empty_flag,
	full_flag, afull_flag 
);

	input rst;
	input [7:0] di;
	input clk, we;
	input re;

	output [7:0] do;
	output empty_flag;
	output full_flag, afull_flag;

EG_LOGIC_FIFO #(
 	.DATA_WIDTH_W(8),
	.DATA_WIDTH_R(8),
	.DATA_DEPTH_W(4096),
	.DATA_DEPTH_R(4096),
	.ENDIAN("BIG"),
	.RESETMODE("SYNC"),
	.E(0),
	.F(4096),
	.ASYNC_RESET_RELEASE("SYNC"),
	.AF(4095))
fifo_inst(
	.rst(rst),
	.di(di),
	.clkw(clk),
	.we(we),
	.csw(3'b111),
	.do(do),
	.clkr(clk),
	.re(re),
	.csr(3'b111),
	.ore(1'b0),
	.empty_flag(empty_flag),
	.aempty_flag(),
	.full_flag(full_flag),
	.afull_flag(afull_flag)

);

endmodule