/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	D:/EG4S20/EG4S20/Codes/rgmii_ethernet/al_ip/IDDR.v
 ** Date	:	2021 08 04
 ** TD version	:	5.0.30786
\************************************************************/

`timescale 1ns / 1ps

module IDDR ( q1, q0, d, clk, rst );
output 		q1;
output 		q0;
input  		d;
input  		clk;
input  		rst;

		EG_LOGIC_IDDR #(
		.ASYNCRST("ENABLE"),
		.PIPEMODE("PIPED"))
		iddr (
		.q1(q1),
		.q0(q0),
		.clk(clk),
		.d(d),
		.rst(rst));

endmodule