/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	D:/EG4S20/EG4S20/Codes/rgmii_ethernet/al_ip/ODDR.v
 ** Date	:	2021 08 04
 ** TD version	:	5.0.30786
\************************************************************/

`timescale 1ns / 1ps

module ODDR ( q, clk, d1, d0, rst );
output 		q;
input  		clk;
input  		d1;
input  		d0;
input  		rst;

		EG_LOGIC_ODDR #(
		.ASYNCRST("ENABLE"))
		oddr (
		.q(q),
		.clk(clk),
		.d1(d1),
		.d0(d0),
		.rst(rst));

endmodule