/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	D:/EG4S20/EG4S20/Codes/rgmii_ethernet/al_ip/Simple_DualRAM.v
 ** Date	:	2021 08 05
 ** TD version	:	5.0.30786
\************************************************************/

`timescale 1ns / 1ps

module Simple_DualRAM ( 
	dia, addra, clka,wea, 
	dob, addrb, clkb
);


	parameter DATA_WIDTH_A = 8; 
	parameter ADDR_WIDTH_A = 11;
	parameter DATA_DEPTH_A = 2048;
	parameter DATA_WIDTH_B = 8;
	parameter ADDR_WIDTH_B = 11;
	parameter DATA_DEPTH_B = 2048;
	parameter REGMODE_A    = "NOREG";
	parameter REGMODE_B    = "NOREG";
	parameter WRITEMODE_A  = "NORMAL";
	parameter WRITEMODE_B  = "READBEFOREWRITE";

	output [DATA_WIDTH_B-1:0] dob;


	input  [DATA_WIDTH_A-1:0] dia;
	input  [ADDR_WIDTH_A-1:0] addra;
	input  [ADDR_WIDTH_B-1:0] addrb;
	input  [0:0] wea;
	input  clka;
	input  clkb;



	EG_LOGIC_BRAM #( .DATA_WIDTH_A(DATA_WIDTH_A),
				.DATA_WIDTH_B(DATA_WIDTH_B),
				.ADDR_WIDTH_A(ADDR_WIDTH_A),
				.ADDR_WIDTH_B(ADDR_WIDTH_B),
				.DATA_DEPTH_A(DATA_DEPTH_A),
				.DATA_DEPTH_B(DATA_DEPTH_B),
				.BYTE_ENABLE(8),
				.BYTE_A(1),
				.BYTE_B(1),
				.MODE("PDPW"),
				.REGMODE_A(REGMODE_A),
				.REGMODE_B(REGMODE_B),
				.WRITEMODE_A(WRITEMODE_A),
				.WRITEMODE_B(WRITEMODE_B),
				.RESETMODE("SYNC"),
				.IMPLEMENT("9K"),
				.INIT_FILE("NONE"),
				.FILL_ALL("NONE"))
			inst(
				.dia(dia),
				.dib({8{1'b0}}),
				.addra(addra),
				.addrb(addrb),
				.cea(1'b1),
				.ceb(1'b1),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(clkb),
				.wea(1'b0),
				.bea(wea),
				.rsta(1'b0),
				.rstb(1'b0),
				.doa(),
				.dob(dob));


endmodule